"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

export type SourceItem={id:string;kind:string;name:string;status:string;last_synced_at?:string|null;last_error?:string|null};
type Connection="checking"|"live"|"offline";
type Job={id:string;kind:string;status:string;attempts:number;max_attempts:number;created_at:string;run_after:string;last_error?:string|null};

async function jsonRequest(path:string,init?:RequestInit){const response=await fetch(path,init);const body=response.status===204?null:await response.json().catch(()=>({}));if(!response.ok)throw new Error(body?.detail||`Request failed (${response.status})`);return body}

export function Sources({items,connection,onCreated}:{items:SourceItem[];connection:Connection;onCreated:(item:SourceItem)=>void}){
 const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [syncing,setSyncing]=useState("");const [notice,setNotice]=useState("");
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);setSaving(true);setError("");setNotice("");try{const provider=String(data.get("provider"));const endpoint=String(data.get("endpoint"));const body={kind:String(data.get("kind")),name:String(data.get("name")),config:provider==="http_json"?{provider,url:endpoint,records_path:"items",id_path:"id",title_path:"title",content_path:"content",credential_env:"LORELINE_CONNECTOR_TOKEN"}:{provider,base_url:endpoint,credential_env:"LORELINE_CONNECTOR_CREDENTIAL"}};const result=await jsonRequest("/api/loreline/v1/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});onCreated(result);form.reset();setOpen(false);setNotice(`${result.name} was connected. Choose Sync now to ingest records.`)}catch(e){setError(e instanceof Error?e.message:"Source failed")}finally{setSaving(false)}};
 const sync=async(item:SourceItem)=>{setSyncing(item.id);setError("");setNotice("");try{await jsonRequest(`/api/loreline/v1/sources/${item.id}/sync`,{method:"POST"});setNotice(`Synchronization for ${item.name} was queued.`)}catch(e){setError(e instanceof Error?e.message:"Synchronization could not be queued")}finally{setSyncing("")}};
 return <div className="page"><div className="page-heading compact"><div><p className="kicker">CONNECTED KNOWLEDGE</p><h1>Sources and synchronization</h1><p>Credentials stay in the secret manager; workers persist cursors and retry failures.</p></div><button className="primary" disabled={connection!=="live"} onClick={()=>setOpen(!open)}>{open?"Close form":"+ Connect source"}</button></div>{connection!=="live"&&<div className="connection-banner">The console is showing sample sources. Connect the production gateway to create and synchronize durable sources.</div>}{notice&&<p className="success-banner" role="status">{notice}</p>}{open&&<form className="panel source-form" onSubmit={create}><label>Name<input name="name" required maxLength={160} placeholder="Company wiki"/></label><label>Type<select name="kind"><option value="wiki">Wiki</option><option value="ticketing">Ticketing</option><option value="drive">Drive</option><option value="api">API</option></select></label><label>Provider<select name="provider"><option value="confluence">Confluence</option><option value="zendesk">Zendesk</option><option value="http_json">Generic JSON API</option></select></label><label>HTTPS endpoint<input name="endpoint" required type="url" pattern="https://.*" placeholder="https://example.atlassian.net"/><small>The hostname must be present in the worker egress allowlist.</small></label><button className="approve" disabled={saving}>{saving?"Connecting…":"Save source"}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>}<section className="source-grid">{items.map(item=><article className="panel source-card" key={item.id}><div className={`source-kind ${item.kind}`}>{item.kind.slice(0,1).toUpperCase()}</div><div><span className={`status ${item.status==="active"?"ok":"wait"}`}>{item.status}</span><h2>{item.name}</h2><p>{item.kind} connector</p><small className={item.last_error?"source-error":""}>{item.last_error||(!item.last_synced_at?"Not synchronized yet":`Last synchronized ${new Date(item.last_synced_at).toLocaleString()}`)}</small></div><button className="outline" disabled={connection!=="live"||syncing===item.id} onClick={()=>void sync(item)}>{syncing===item.id?"Queueing…":"Sync now"}</button></article>)}</section>{!items.length&&<div className="panel table-empty">No sources connected. Add a source to begin ingestion.</div>}{error&&!open&&<p className="form-error" role="alert">{error}</p>}</div>
}

export function Operations({connection}:{connection:Connection}){
 const [jobs,setJobs]=useState<Job[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [replaying,setReplaying]=useState("");
 const load=useCallback(async()=>{if(connection!=="live")return;setLoading(true);setError("");try{const result=await jsonRequest("/api/loreline/v1/jobs?limit=100");setJobs(result.items||[])}catch(e){setError(e instanceof Error?e.message:"Jobs unavailable")}finally{setLoading(false)}},[connection]);
 useEffect(()=>{if(connection!=="live")return;let active=true;fetch("/api/loreline/v1/jobs?limit=100").then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.detail||"Jobs unavailable");if(active)setJobs(body.items||[])}).catch(error=>{if(active)setError(error instanceof Error?error.message:"Jobs unavailable")});return()=>{active=false}},[connection]);
 const replay=async(id:string)=>{setReplaying(id);setError("");try{await jsonRequest(`/api/loreline/v1/jobs/${id}/replay`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Job replay failed")}finally{setReplaying("")}};
 const counts=(name:string)=>jobs.filter(j=>j.status===name).length;
 return <div className="page"><div className="page-heading compact"><div><p className="kicker">OPERATIONS</p><h1>Durable work, visible</h1><p>Inspect queue health, retries, worker leases, scheduling, and dead-letter jobs.</p></div><button className="outline" disabled={connection!=="live"||loading} onClick={()=>void load()}>{loading?"Refreshing…":"Refresh"}</button></div><div className="metric-grid"><Metric label="Queued" value={counts("queued")}/><Metric label="Running" value={counts("running")}/><Metric label="Failed" value={counts("failed")}/><Metric label="Dead letter" value={counts("dead")}/></div>{connection!=="live"?<div className="connection-banner">Operational jobs appear here when the production gateway is connected.</div>:<section className="panel table-scroll"><table><thead><tr><th>Job</th><th>Kind</th><th>Status</th><th>Attempts</th><th>Scheduled</th><th>Error</th><th>Action</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td><code>{job.id.slice(0,12)}</code></td><td>{job.kind}</td><td><span className={`status ${job.status==="succeeded"?"ok":job.status==="dead"?"bad":"wait"}`}>{job.status}</span></td><td>{job.attempts} / {job.max_attempts}</td><td>{new Date(job.run_after).toLocaleString()}</td><td title={job.last_error||""}>{job.last_error?job.last_error.slice(0,60):"—"}</td><td>{(job.status==="failed"||job.status==="dead")&&<button className="outline" disabled={replaying===job.id} onClick={()=>void replay(job.id)}>{replaying===job.id?"Replaying…":"Replay"}</button>}</td></tr>)}</tbody></table>{!loading&&!jobs.length&&<div className="table-empty">No jobs have been created yet.</div>}</section>}{error&&<p className="form-error" role="alert">{error}</p>}</div>
}
function Metric({label,value}:{label:string;value:number}){return <article className="metric ops-metric"><div><span>{label}</span><b>{value}</b><small>Current queue</small></div></article>}
