"use client";
import { FormEvent, useEffect, useState } from "react";

export type SourceItem={id:string;kind:string;name:string;status:string;last_synced_at?:string|null;last_error?:string|null};
type Connection="checking"|"live"|"offline";

export function Sources({items,connection,onCreated}:{items:SourceItem[];connection:Connection;onCreated:(item:SourceItem)=>void}){
 const [open,setOpen]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);setSaving(true);setError("");try{const provider=String(data.get("provider"));const endpoint=String(data.get("endpoint"));const body={kind:String(data.get("kind")),name:String(data.get("name")),config:provider==="http_json"?{provider,url:endpoint,records_path:"items",id_path:"id",title_path:"title",content_path:"content",credential_env:"LORELINE_CONNECTOR_TOKEN"}:{provider,base_url:endpoint,credential_env:"LORELINE_CONNECTOR_CREDENTIAL"}};const response=await fetch("/api/loreline/v1/sources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.detail||"Source could not be created");onCreated(result);setOpen(false)}catch(e){setError(e instanceof Error?e.message:"Source failed")}finally{setSaving(false)}};
 const sync=async(id:string)=>{const response=await fetch(`/api/loreline/v1/sources/${id}/sync`,{method:"POST"});if(!response.ok)setError("Synchronization could not be queued")};
 return <div className="page"><div className="page-heading compact"><div><p className="kicker">CONNECTED KNOWLEDGE</p><h1>Sources and synchronization.</h1><p>Credentials stay in the secret manager; workers persist cursors and retry failures.</p></div><button className="primary" disabled={connection!=="live"} onClick={()=>setOpen(!open)}>+ Connect source</button></div>{connection!=="live"&&<div className="connection-banner">The console is showing demo sources. Connect the production gateway to create and synchronize durable sources.</div>}{open&&<form className="panel source-form" onSubmit={create}><label>Name<input name="name" required maxLength={160} placeholder="Company wiki"/></label><label>Type<select name="kind"><option value="wiki">Wiki</option><option value="ticketing">Ticketing</option><option value="drive">Drive</option><option value="api">API</option></select></label><label>Provider<select name="provider"><option value="confluence">Confluence</option><option value="zendesk">Zendesk</option><option value="http_json">Generic JSON API</option></select></label><label>Endpoint<input name="endpoint" required type="url" placeholder="https://example.atlassian.net"/></label><button className="approve" disabled={saving}>{saving?"Connecting…":"Save source"}</button>{error&&<p className="form-error">{error}</p>}</form>}<section className="source-grid">{items.map(item=><article className="panel source-card" key={item.id}><div className={`source-kind ${item.kind}`}>{item.kind.slice(0,1).toUpperCase()}</div><div><span className={`status ${item.status==="active"?"ok":"wait"}`}>{item.status}</span><h2>{item.name}</h2><p>{item.kind} connector</p><small>{item.last_error||(!item.last_synced_at?"Not synchronized yet":`Last synchronized ${new Date(item.last_synced_at).toLocaleString()}`)}</small></div><button className="outline" disabled={connection!=="live"} onClick={()=>sync(item.id)}>Sync now</button></article>)}</section></div>
}

export function Operations({connection}:{connection:Connection}){
 const [jobs,setJobs]=useState<Array<Record<string,unknown>>>([]);const [error,setError]=useState("");
 const load=async()=>{if(connection!=="live")return;try{const response=await fetch("/api/loreline/v1/jobs?limit=100");const result=await response.json();if(!response.ok)throw new Error(result.detail||"Jobs unavailable");setJobs(result.items||[])}catch(e){setError(e instanceof Error?e.message:"Jobs unavailable")}};
 useEffect(()=>{if(connection!=="live")return;let cancelled=false;fetch("/api/loreline/v1/jobs?limit=100").then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.detail||"Jobs unavailable");if(!cancelled)setJobs(result.items||[])}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:"Jobs unavailable")});return()=>{cancelled=true}},[connection]);const replay=async(id:string)=>{await fetch(`/api/loreline/v1/jobs/${id}/replay`,{method:"POST"});await load()};
 const counts=(name:string)=>jobs.filter(j=>j.status===name).length;
 return <div className="page"><div className="page-heading compact"><div><p className="kicker">OPERATIONS</p><h1>Durable work, visible.</h1><p>Inspect queue health, retries, worker leases, and dead-letter jobs.</p></div><button className="outline" onClick={load}>Refresh</button></div><div className="metric-grid"><Metric label="Queued" value={counts("queued")}/><Metric label="Running" value={counts("running")}/><Metric label="Failed" value={counts("failed")}/><Metric label="Dead letter" value={counts("dead")}/></div>{connection!=="live"?<div className="connection-banner">Operational jobs appear here when the production gateway is connected.</div>:<section className="panel library"><table><thead><tr><th>Job</th><th>Kind</th><th>Status</th><th>Attempts</th><th>Created</th><th>Action</th></tr></thead><tbody>{jobs.map(job=><tr key={String(job.id)}><td><b>{String(job.id).slice(0,12)}</b></td><td>{String(job.kind)}</td><td><span className={`status ${job.status==="succeeded"?"ok":"wait"}`}>{String(job.status)}</span></td><td>{String(job.attempts)} / {String(job.max_attempts)}</td><td>{new Date(String(job.created_at)).toLocaleString()}</td><td>{(job.status==="failed"||job.status==="dead")&&<button className="outline" onClick={()=>replay(String(job.id))}>Replay</button>}</td></tr>)}</tbody></table>{!jobs.length&&<div className="table-empty">No jobs have been created yet.</div>}</section>}{error&&<p className="form-error">{error}</p>}</div>
}
function Metric({label,value}:{label:string;value:number}){return <article className="metric ops-metric"><div><span>{label}</span><b>{value}</b><small>Current queue</small></div></article>}
